name: api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  broadcast_bloc: ^0.1.0-dev.1
  dart_frog: ^0.3.0
  dart_frog_web_socket: ^0.1.0-dev.2
  equatable: ^2.0.5
  http: ^0.13.5

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
